#ifndef FILE_TYPE_H
#define FILE_TYPE_H

enum FILE_TYPE
{
	FILE_TYPE_UNKNOWN,
	FILE_TYPE_FOLDER,
	FILE_TYPE_TXT,
	FILE_TYPE_GLSL,
	FILE_TYPE_HLSL,
	FILE_TYPE_C_HEADER,
	FILE_TYPE_C_SRC,
	FILE_TYPE_CPP_SRC,
	FILE_TYPE_JSON,
	FILE_TYPE_SPIRV,
	FILE_TYPE_GLB,
	FILE_TYPE_GMESH,
	FILE_TYPE_OBJ,
	FILE_TYPE_GLTF
};

#endif // FILE_TYPE_H