#ifndef RESOURCE_INIT_CODE_H
#define RESOURCE_INIT_CODE_H

enum RESOURCE_INIT_CODE
{
	RESOURCE_INIT_CODE_OK = 0,
	RESOURCE_INIT_CODE_UNKNOWN_EX = 1,
	RESOURCE_INIT_CODE_FILE_NOT_FOUND = 2
};

#endif // RESOURCE_INIT_CODE_H