#ifndef IVULKAN_GRAPHIC_PIPELINE_STATE_H
#define IVULKAN_GRAPHIC_PIPELINE_STATE_H

enum GRAPHIC_PIPELINE_STATE
{
	GRAPHIC_PIPELINE_STATE_VERTEX_INPUT,
	GRAPHIC_PIPELINE_STATE_INPUT_ASSEMBLY,
	GRAPHIC_PIPELINE_STATE_TESSALATION,
	GRAPHIC_PIPELINE_STATE_VIEWPORT,
	GRAPHIC_PIPELINE_STATE_RASTERIZATION,
	GRAPHIC_PIPELINE_STATE_MULTISAMPLE,
	GRAPHIC_PIPELINE_STATE_DEPTH_STENCIL,
	GRAPHIC_PIPELINE_STATE_COLOR_BLEND,
	GRAPHIC_PIPELINE_STATE_DYNAMIC
};

struct VkGraphicsPipelineCreateInfo;

class IGVulkanGraphicPipelineState
{
public:
	virtual ~IGVulkanGraphicPipelineState() = default;

	virtual GRAPHIC_PIPELINE_STATE get_pipeline_state() = 0;

	virtual void fill_pipeline_create_info(VkGraphicsPipelineCreateInfo* createInfo) = 0;
private:
};

#endif // IVULKAN_GRAPHIC_PIPELINE_STATE_H