#ifndef GPROPERTY_ERRORS_H
#define GPROPERTY_ERRORS_H

enum GPROPERTY_GET_ERROR
{
	GPROPERTY_GET_ERROR_INVALID_PROPERTY,
	GPROPERTY_GET_ERROR_INVALID_OBJECT
};


enum GPROPERTY_SET_ERROR
{
	GPROPERTY_SET_ERROR_INVALID_PROPERTY,
	GPROPERTY_SET_ERROR_INVALID_OBJECT,
	GPROPERTY_SET_ERROR_PROPERTY_WAS_NATIVE_CONST,
	GPROPERTY_SET_ERROR_INVALID_PROPERTY_TYPE
};

#endif // GPROPERTY_ERRORS_H